#!/bin/sh

dirname=$(dirname "$(readlink -f "$0")")
node_modules="$(readlink -f "$dirname/../node_modules/.bin")"
PATH="$PATH:$node_modules"

usage () {
  printf 'Usage: script/start [options]'
}

test_static () {
  dependency-check . || exit 1
  dependency-check . --extra --no-dev \
    -i tachyons -i insert-css \
    --entry client.js || exit 1
  standard || exit 1
  standard-markdown || exit 1
}

test_all () {
  test_static || exit 1
}

# set CLI flags
args="$(getopt sah "$*")"
[ $? -ne 0 ] && { usage; exit 2; }
eval set -- "$args"

# parse CLI flags
while true; do
  case "$1" in
    -h ) usage ;;
    -s ) shift; test_static; break ;;
    -a|* ) shift; test_all; break ;;
  esac
done
